version: 2
updates:
  - package-ecosystem: github-actions
    target-branch: master
    directory: /
    schedule:
      interval: weekly
    assignees:
      - denniskrol
    groups:
      github:
        patterns:
          - "*"

  - package-ecosystem: npm
    target-branch: master
    directories:
      - "/frontend"
      - "/backend"
      - "/models"
    schedule:
      interval: weekly
    assignees:
      - denniskrol
    groups:
      npm:
        patterns:
          - "*"
